# Generated by Django 5.2.8 on 2025-11-21 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codigo_externo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "conjunto",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(blank=True, max_length=50, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "perfil",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.TextField()),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="Lider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.perfil",
                    ),
                ),
            ],
            options={
                "db_table": "lider",
            },
        ),
        migrations.CreateModel(
            name="Asesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.perfil",
                    ),
                ),
            ],
            options={
                "db_table": "asesor",
            },
        ),
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(blank=True, null=True)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "lider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.lider",
                    ),
                ),
            ],
            options={
                "db_table": "ruta",
            },
        ),
        migrations.CreateModel(
            name="PuntoVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.IntegerField(blank=True, null=True)),
                ("ventana_inicio", models.TimeField(blank=True, null=True)),
                ("ventana_fin", models.TimeField(blank=True, null=True)),
                (
                    "conjunto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.conjunto",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.ruta",
                    ),
                ),
            ],
            options={
                "db_table": "punto_visita",
            },
        ),
        migrations.CreateModel(
            name="AsignacionRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asesor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.asesor",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.ruta",
                    ),
                ),
            ],
            options={
                "db_table": "asignacion_ruta",
            },
        ),
        migrations.AddField(
            model_name="perfil",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="gestion.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("precision", models.CharField(blank=True, max_length=50, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "asesor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.asesor",
                    ),
                ),
                (
                    "punto_visita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.puntovisita",
                    ),
                ),
            ],
            options={
                "db_table": "visita",
            },
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_url", models.TextField(blank=True, null=True)),
                ("hash_integridad", models.TextField(blank=True, null=True)),
                ("exif_resumen", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "visita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestion.visita",
                    ),
                ),
            ],
            options={
                "db_table": "evidencia",
            },
        ),
    ]
