# Generated by Django 5.2.8 on 2025-11-21 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="visita",
            name="asesor",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.perfil",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="asignacionruta",
            name="asesor",
        ),
        migrations.RemoveField(
            model_name="asignacionruta",
            name="ruta",
        ),
        migrations.RemoveField(
            model_name="lider",
            name="perfil",
        ),
        migrations.AlterField(
            model_name="ruta",
            name="lider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutas_creadas",
                to="gestion.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="usuario",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="puntovisita",
            options={"ordering": ["orden"]},
        ),
        migrations.RenameField(
            model_name="puntovisita",
            old_name="ventana_fin",
            new_name="hora_fin_estimada",
        ),
        migrations.RenameField(
            model_name="puntovisita",
            old_name="ventana_inicio",
            new_name="hora_inicio_estimada",
        ),
        migrations.RenameField(
            model_name="visita",
            old_name="observacion",
            new_name="observaciones",
        ),
        migrations.RemoveField(
            model_name="conjunto",
            name="codigo_externo",
        ),
        migrations.RemoveField(
            model_name="conjunto",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="conjunto",
            name="lng",
        ),
        migrations.RemoveField(
            model_name="evidencia",
            name="creado_en",
        ),
        migrations.RemoveField(
            model_name="evidencia",
            name="exif_resumen",
        ),
        migrations.RemoveField(
            model_name="evidencia",
            name="foto_url",
        ),
        migrations.RemoveField(
            model_name="ruta",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="checkin_ts",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="lng",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="precision",
        ),
        migrations.AddField(
            model_name="conjunto",
            name="latitud",
            field=models.DecimalField(
                decimal_places=7, default=0, help_text="Latitud esperada", max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conjunto",
            name="longitud",
            field=models.DecimalField(
                decimal_places=7,
                default=0,
                help_text="Longitud esperada",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evidencia",
            name="archivo_foto",
            field=models.ImageField(default="", upload_to="evidencias/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evidencia",
            name="fecha_captura",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="perfil",
            name="zona",
            field=models.CharField(
                blank=True,
                help_text="Zona asignada (ej: Caldas)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="asesor_asignado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutas_asignadas",
                to="gestion.perfil",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ruta",
            name="fecha_programada",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="visita",
            name="fecha_hora_checkin",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visita",
            name="latitud_registro",
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="visita",
            name="longitud_registro",
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="visita",
            name="precision_gps",
            field=models.FloatField(help_text="Precisión del GPS en metros", null=True),
        ),
        migrations.AlterField(
            model_name="conjunto",
            name="ciudad",
            field=models.CharField(default="Manizales", max_length=100),
        ),
        migrations.AlterField(
            model_name="conjunto",
            name="direccion",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conjunto",
            name="nombre",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evidencia",
            name="hash_integridad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="evidencia",
            name="visita",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidencias",
                to="gestion.visita",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="perfil",
            name="rol",
            field=models.CharField(
                choices=[("LIDER", "Líder de Zona"), ("ASESOR", "Asesor Comercial")],
                default="ASESOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="puntovisita",
            name="conjunto",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.conjunto",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="puntovisita",
            name="orden",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="puntovisita",
            name="ruta",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puntos",
                to="gestion.ruta",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ruta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PLAN", "En Planificación"),
                    ("ACTIVA", "En Curso"),
                    ("CERRADA", "Finalizada"),
                ],
                default="PLAN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ruta",
            name="nombre",
            field=models.CharField(
                default="", help_text="Ej: Ruta Centro - Lunes", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("REALIZADA", "Realizada / Check-in OK"),
                    ("NO_REALIZADA", "No se pudo realizar"),
                ],
                default="REALIZADA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visita",
            name="punto_visita",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visita_realizada",
                to="gestion.puntovisita",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="conjunto",
            table=None,
        ),
        migrations.AlterModelTable(
            name="evidencia",
            table=None,
        ),
        migrations.AlterModelTable(
            name="perfil",
            table=None,
        ),
        migrations.AlterModelTable(
            name="puntovisita",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ruta",
            table=None,
        ),
        migrations.AlterModelTable(
            name="visita",
            table=None,
        ),
        migrations.DeleteModel(
            name="Asesor",
        ),
        migrations.DeleteModel(
            name="AsignacionRuta",
        ),
        migrations.DeleteModel(
            name="Lider",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
